PR for dap issue #16 section 6.1
savvy-coders/dap-curriculum pull request #18
Opened 2023-01-02 18:47 UTC by JohanBester

Hi Folks,
I finished work on section 6.1
Kindly please review this PR and let me know what improvements or corrections need to be made here
Thanks

2023-01-04 13:51 UTC, coyoteJohn reviewed
There is a typo at 1289 but it is in an exercise block. Is that for the students to find?
I need to pull this to test the code blocks and I will try to get that done this morning.

2023-01-10 01:28 UTC, jamesleemeredith commented on Section06/6.1-Python_FlowControl.ipynb
> +    "To make this non-sequential flow possible all programming language have a set of control structures which allow this to happen.\n",
Typo here: Should read "... all programming languages..."

2023-01-10 01:29 UTC, jamesleemeredith commented on Section06/6.1-Python_FlowControl.ipynb
> +    "The problem with sequential statements is that if the logic has broken in any one of the lines, then the complete source code execution will break, and stop at that point of error.\n",
Typo here: I believe it should read "... if the logic is broken in any..."

2023-01-10 01:40 UTC, jamesleemeredith requested changes
Noticed one or two typos and commented on the appropriate lines.

2023-01-10 02:40 UTC, JohanBester commented on Section06/6.1-Python_FlowControl.ipynb
> +    "To make this non-sequential flow possible all programming language have a set of control structures which allow this to happen.\n",
Thanks James, got that one fixed

2023-01-10 02:43 UTC, JohanBester commented on Section06/6.1-Python_FlowControl.ipynb
> +    "The problem with sequential statements is that if the logic has broken in any one of the lines, then the complete source code execution will break, and stop at that point of error.\n",
Thanks, I got this one as well  :)

2023-01-10 02:48 UTC, coyoteJohn approved these changes
Looks good.

2023-01-10 03:58 UTC, jamesleemeredith approved these changes

2023-01-10 04:02 UTC, merged