PR for issue Dap-20
savvy-coders/dap-curriculum pull request #28
Opened 2023-01-10 21:37 UTC by Danielle0727

I added two images in Section 2 and named them "ExcelAND.jpg" and "ExcelAVERAGEIF.jpg". These were images that were included in the PPT. I also created a table for the Functions. Please let me know if you do not want them in table format or have suggestions on how to make is easier to view. I welcome any and all feedback, especially since this is my first time doing markdown for the curriculum.

2023-01-10 22:54 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +# <div align="center">&#8681;</div>
I suggest we not center these sections

2023-01-10 22:56 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +![Excel_Practice_Student.xlsx](./activities/Excel_Practice_Student.xlsx)
This link not working as this is setup as an image. Removing the exclamation mark will make the link work

2023-01-10 22:57 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +![Data Wrangling](./img/DataWranglingSteps.png)
Often layout is enhanced by adding a break mark on a blank line between sections like here below 

<br>

2023-01-10 23:03 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +|<font color=blue>If a number is greater than or smaller than another number or is equal to something.</font> | Produces whatever outcome you need it to read if you don’t want “True” or “False” … |
I suggest we shy away from using dark blue due to poor contrast issue in dark mode environments. Kindly please change the color of just use the default text color.

![Screenshot 2023-01-10 170249](https://user-images.githubusercontent.com/29065848/211680574-1744a55c-2a51-4b73-906a-5b120a823de8.png)

2023-01-10 23:06 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +
I hate suggesting this as it will create additional work. However, after looking at this online and offline, it might be beater if the functions are not put in a table.
Instead just one after another from top down type of layout would be easier on the eye.

2023-01-10 23:09 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +
Again I would advise against using dark font because of possible conflicts with dark mode environments

![Screenshot 2023-01-10 170741](https://user-images.githubusercontent.com/29065848/211681339-42168d8f-c942-4759-b167-b87cd4bb3284.png)

2023-01-10 23:11 UTC, JohanBester requested changes
Hi Danielle,
You did great!
I did leave several comments regarding style more than anything else.
Also a comment about the Excel Student worksheet link that does not show at this stage.
Let me know if there are any questions or you need clarification on any point.

2023-01-11 15:08 UTC, Danielle0727 commented on Section02/2.3-DAPandExcel.md
> +![Excel_Practice_Student.xlsx](./activities/Excel_Practice_Student.xlsx)
Removed exclamation mark

2023-01-11 15:11 UTC, Danielle0727 commented on Section02/2.3-DAPandExcel.md
> +![Data Wrangling](./img/DataWranglingSteps.png)
I completely agree! I added further breaks to the entire document.

2023-01-11 15:19 UTC, Danielle0727 commented on Section02/2.3-DAPandExcel.md
> +|<font color=blue>If a number is greater than or smaller than another number or is equal to something.</font> | Produces whatever outcome you need it to read if you don’t want “True” or “False” … |
I removed the color in that area, as well as under VLOOKUP. Since I removed the color under VLOOKUP, I added in paranthesis what each description is referring to, in order to make it easier for the students. In the excel sheet, I believe there were colors to help identify what each description was referring to, but please let me know if you would like me to remove my addition.

2023-01-11 15:20 UTC, Danielle0727 commented on Section02/2.3-DAPandExcel.md
> +
No worries! It's all a learning process and I don't mind fixing it. I want to make it easy to read for the students.

2023-01-11 16:07 UTC, Danielle0727 commented on Section02/2.3-DAPandExcel.md
> +
Thank you Johan for all of the suggestions and feedback. I made all of the changes you suggested, and realized I may have overdone it on my replies and I could have just sent one reply.

2023-01-12 01:14 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +- `=AND=AND([logical1], [logical2], ...)`
I think the slide had an error here.
I believe that line should just be `=AND([logical1], [logical2], ...)`
Sorry I missed this the 1st time

2023-01-12 01:23 UTC, JohanBester commented on Section02/2.3-DAPandExcel.md
> +
I just noticed that this section is a little confusing.
I want to propose a little reorganization if you don't mind please.
I suggest this order:-

Delete this line
(  ### =AVERAGEIFS(C27:C38, B27:B38, F28, D27:D38,G28)  )

**AVERAGEIFS**
- Calculates the average of a range based on one or more true/false conditions
- `=AVERAGEIFS(average_range, criteria_range1, criteria1, ...)`
- `=AVERAGEIFS(C27:C38, B27:B38, F28, D27:D38,G28)`

`<br>`

**AVERAGEIF**  
- Combine averages from different cells
- `=AVERAGEIF(range, criteria, [average_range])`

![Screenshot 2023-01-11 191634](https://user-images.githubusercontent.com/29065848/211952784-0c101073-aadf-4997-a76b-387c5654ef94.png)

2023-01-12 01:33 UTC, JohanBester requested changes
The changes you made are great.
I made a few more suggestions if you don't mind.
Also, maybe add a small Intro at the top of the section, and a small summary at the end.
Thanks!  :)

2023-01-12 21:22 UTC, Danielle0727 commented
-Removed the extra AND in =AND([logical1], [logical2], ...)
-Made updates to the AVERAGEIF(S) feedback. 
-Updated the AVERAGEIF image. 
-Added an Objective and Summary section.

2023-01-13 16:44 UTC, merged