PR for Issue Dap-23
savvy-coders/dap-curriculum pull request #29
Opened 2023-01-11 14:23 UTC by HollymRobinson

Need to add slides 16 and 17 from Tableauday1.pptx open to suggestions on how to go about embedding the content.

2023-01-11 15:00 UTC, Danielle0727 reviewed
Great job!

2023-01-11 15:00 UTC, Danielle0727 commented on Section09/Tableauno1.md
> +- will change raw data into data that is easy to understand
One tiny grammar suggestion. Capitolize 'w' in will.

2023-01-11 15:00 UTC, Danielle0727 commented on Section09/Tableauno1.md
> +- Automatic & contrext aware
Contrext - possible misspelling.

2023-01-11 15:00 UTC, Danielle0727 commented on Section09/Tableauno1.md
> +1. Connect two sources (Superstore & GLobal Superstore)
Capitol L in global.

2023-01-12 00:35 UTC, JohanBester commented on Section09/Tableauno1.md
> +## AS A DATA ANALYST
This is a style point: Maybe try adding a break between session so that there is white space on the page to help separate sections and give the eye a break from a wall of text. Like so...

"`<br>`"

2023-01-12 00:38 UTC, JohanBester commented on Section09/Tableauno1.md
> +## Examples
It might be useful and clearer if we expand this title here to say something more descriptive than just examples. For example "Examples of what Data Analytics encompasses" (obviously something relevant to the section)

2023-01-12 00:42 UTC, JohanBester commented on Section09/Tableauno1.md
> +- Dashboards are preps for your STORY (aka presentation)
I'd suggest to place quotes around the word "preps" as it is a custom term

2023-01-12 00:44 UTC, JohanBester commented on Section09/Tableauno1.md
> +
Suggestion for these steps: Make them a little more descriptive so it is easier tot follow these instructions

2023-01-12 00:46 UTC, JohanBester commented on Section09/Tableauno1.md
> +- Right Join: values from RIGHT Table & matchto LEFT Table
Should "matchto" be two words, or not?

2023-01-12 00:49 UTC, JohanBester commented on Section09/Tableauno1.md
> +---
Consider adding a small intro at the beginning, and a summary at the end. Just a suggestion

2023-01-12 00:50 UTC, JohanBester requested changes
Great start here. 
I made a few suggestions for edits and changes.
Let me know if there are questions.

2023-01-12 13:30 UTC, JohanBester submitted a review, later dismissed
I approve

2023-01-14 18:10 UTC, JohanBester approved these changes
Approved

2023-01-14 18:11 UTC, merged