Converted Tableau Day 2 to Markdown
savvy-coders/dap-curriculum pull request #30
Opened 2023-01-12 09:27 UTC by jamesleemeredith

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +### Let’s Try it Using the Sample Superstore Data:
Suggestion on formatting, however, this is my own personal style I like to use so please use your better judgment on what you like best. For items you want them to click on, you could put them in brackets and bold them. For example, "Drag [**Sales**] to "Rows", ..."

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +### Dimensions vs. Measures​
Maybe add that Dimensions are in green and Measures are in blue. That helped me a lot when I was a student and it pointed out.

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +![Discrete Data Types in Tableau](images\Discrete_data_graph.png)
The links say "Data not found". May have to remove the "!". I had the same thing happen with one of mine and removing the exclamation point fixed it. I think "!" is only used with images.

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +### Changing a whole number field to a decimal (and vis versa):
Vice Versa typo.

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +- Individual data points and be given aliases in Tableau
May want to remove "be".

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +    - General: selects one or multiple members from the domain​
May help the reader to bold **General"", ""Wildcard**, **Condition**, and **Top**

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +- Types of measure filters:
May help to bold these as well: **Range of Values**, **At Least**, **At Most**, **Special**

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +    - Relative Dates: can specify a range of dates that are updated based on the date and time
If you choose to bold, I included the markdown for ease of copying and pasting: **Relative Dates**, **Range of Dates**, **Discrete Dates**, **Individual Dates**, **Additional Date Filter Options**

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +- Created by right-clicking on a field and selecting "Create" > "Bins​"
If you wanted to include an actual arrow pointing right, here is the markdown code: 

&rarr;

2023-01-12 21:54 UTC, Danielle0727 commented on Section09/9.2-Tableau.md
> +- Options for charts and be selecting by clicking on the “Show Me” button on the upper right corner​ of the task bar
I wasn't sure if "be selecting" was meant to say "by selecting"

2023-01-13 01:59 UTC, JohanBester commented on Section09/9.2-Tableau.md
> +- Individual data points and be given aliases in Tableau
I think you wanted to write ...
"Individual data points can be given aliases in Tableau"

2023-01-13 02:03 UTC, JohanBester commented on Section09/9.2-Tableau.md
> +- Options for charts and be selecting by clicking on the “Show Me” button on the upper right corner​ of the task bar
I think you meant to say ...
"Charts are often easier to understand than tables with numbers​,"

2023-01-13 02:06 UTC, JohanBester requested changes
James I reviewed your PR and made a few inline comments.

Apart from those and what I communicated with you on Slack, I have one last style suggestion:

You might want to add a small little intro to the top of the section, and a small summary to the bottom of the section

2023-01-13 12:41 UTC, HollymRobinson commented on Section09/9.2-Tableau.md
> +## The Data interpreter
Suggestion: ## The Data Interpreter

2023-01-13 12:43 UTC, HollymRobinson commented on Section09/9.2-Tableau.md
> +### To create a pivot
Suggestion: ### To Create a Pivot

2023-01-13 13:05 UTC, HollymRobinson reviewed
Only suggestion two minor edits. Good job!

2023-01-13 13:05 UTC, HollymRobinson commented on Section09/9.2-Tableau.md
> +
Good Job! I will add bolding to my markdowns for consistency.

2023-01-14 00:04 UTC, HollymRobinson commented on Section09/9.2-Tableau.md
> +---
copy pasted from lines 66 to 109

2023-01-14 17:36 UTC, JohanBester approved these changes
Approved. Let's merge it!  :)

2023-01-14 17:43 UTC, merged