Pr for Issue Dap-26
savvy-coders/dap-curriculum pull request #32
Opened 2023-01-13 12:33 UTC by HollymRobinson

Awaiting 2 approvals.

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +# Fixed Level of Detail Example
May help the students for the first header to say "Tableau" or "Tableau Continued"

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +Useful when you want to calculate at a fine level of detail in the database and then re-aggregate and show at a coarser level of detail in your view. Fields based on INCLUDE level of detail expressio
May help to reword the last sentence. "Fields based on INCLUDE level..."

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +        Shows the difference between the sum of sales (somewhere between $390k and 700k per region) AND the avg sales per customer (between 750 and 1100 per region)
Suggest creating two lines for this sentence, only because markdown recognizes it as one long running sentence and the students would have to use the horizontal scroll bar to view the remaining sentence.

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +        Shades the view to show total sales by month w/o regional component
May help to spell out w/o. Some students may not be familiar with that abbreviation.

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +Use trend lines in predicting of given data (linear, logarithmic, exponential and polynomial).
In markdown it show the second and third sentence as one long running sentence. May just need to put a space or period between "Summarizing" and "Use"

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +2. Tiled: Fixed Location & Floating: unfixed Location
May help the reader to bold any lettering to the left of colons (:)

2023-01-13 17:28 UTC, Danielle0727 commented on Section09/Tableauday4.md
> +
Great job on everything! Only minor things I saw, but overall looks really great. I read your comment to James about adding the brackets and bold lettering to things you click on, and agree with you that the consistency would help the students :)

2023-01-14 00:16 UTC, JohanBester commented on Section09/Tableauday4.md
> +## SUMMARY:
Maybe this summary should probably be at the top of the section below the heading and before the section content

2023-01-14 00:19 UTC, JohanBester commented on Section09/Tableauday4.md
> +
The wording here needs a little rewrite I think, maybe something like --
"In this section we will discuss some of the basic graph types in Tableau, as well as begin a brief discussion on .. "

2023-01-14 00:27 UTC, JohanBester requested changes
Hi Holly,
I made a suggestion about the first part of the section that does not seem to be in the exact correct order.

The rest is good for the first iteration -- it is much better that the slides  :)
Thanks!

2023-01-14 18:41 UTC, JohanBester approved these changes
Approved

2023-01-14 18:42 UTC, merged