Dap-34 update homework and resources
savvy-coders/dap-curriculum pull request #45
Opened 2023-02-06 04:41 UTC by JohanBester

---
name: Pull Request
about: 'Updated Homework and resources'
title: 'DAP-34: [Create a homework file in each section#34](https://github.com/savvy-coders/dap-curriculum/issues/34)'
assignees: 'Johan'

---

Hello Folks,
I have made significant updates to the structure of the curriculum sections by adding homework and resources. The structure is now the same for every section with  placeholder folders for future additions.
Please review these proposed changes and additions.
Let me know what needs to be corrected please.
Thanks.

Issue Link: [DAP-34](https://github.com/savvy-coders/dap-curriculum/issues/34)

2023-02-07 19:13 UTC, Danielle0727 reviewed
Just a few grammatical things I noticed. The only suggestion I really have is for all of the homework sections, being more specific with the commands (e.g., git add., git commit -m "message" and git push). Also, providing a general breakdown on the Jira tickets (e.g., making sure name is included as well as any descriptions, links, screenshots). The reason I thought about this is because this cohort has had some difficulties in understanding what is needed.

2023-02-07 19:13 UTC, Danielle0727 commented on Section04/resources/4-homework.md
> +3. Write a block of code to handle on of the most common Python exception errors. Select one of the common errors from the curriculum section on Python Exception handling. Have your code example has
add an "e" at the end of "one", after the word handle. Maybe take out "has uses" in "Have you code example has uses the"

2023-02-10 16:05 UTC, matsinet requested changes

2023-02-13 14:47 UTC, matsinet requested changes

2023-02-13 14:47 UTC, matsinet commented on Section00/0-Syllabus.md
>  #### Instructors: -
@JohanBester let me clarify,   I do NOT want any names to be listed in the curriculum.   This should be announced during the orientation night and not documented.   Please let me know if you feel that it is necessary.

2023-02-13 15:53 UTC, matsinet approved these changes

2023-02-14 03:07 UTC, merged